# Generated by Django 4.2.5 on 2023-12-05 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Saving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoVennDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.TextField()),
                ('field2', models.TextField()),
                ('field3', models.TextField()),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThreeVennDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.TextField()),
                ('field2', models.TextField()),
                ('field3', models.TextField()),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='threeproblemstatement',
            name='venn_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Saving.threevenndiagram'),
        ),
        migrations.AlterField(
            model_name='twoproblemstatement',
            name='venn_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Saving.twovenndiagram'),
        ),
        migrations.DeleteModel(
            name='VennDiagram',
        ),
    ]
