# Generated by Django 4.2.5 on 2024-01-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threevenndiagram',
            name='filter',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='twovenndiagram',
            name='filter',
            field=models.TextField(null=True),
        ),
    ]
