# Generated by Django 4.2.5 on 2023-12-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saving', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threeproblemstatement',
            name='statement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='twoproblemstatement',
            name='statement',
            field=models.TextField(),
        ),
    ]
