# Generated by Django 4.2.5 on 2023-12-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saving', '0002_twovenndiagram_threevenndiagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threevenndiagram',
            name='field3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twovenndiagram',
            name='field3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
