# Generated by Django 4.2.5 on 2023-12-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Saving', '0003_alter_threevenndiagram_field3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threeproblemstatement',
            old_name='fk',
            new_name='user_fk',
        ),
    ]
